
using System;
using System.Security.Cryptography;
using System.Xml.Linq;

namespace Vidzy
{
    class Program
    {
        static void AddNewVideo()
        {
            // Foreign key for Action genre
            byte action = 2;

            // Video object
            var newVideo = new Video
            {
                Name = "Terminator 1",
                ReleaseDate = new DateTime(1984, 10, 26),
                GenreId = action, // this avoids duplicating the Genre object by using new Genre() constructor
                Classification = Classification.Silver,
            };

            // Adding newVideo to the database
            using (var context = new VidzyContext())
            {
                context.Videos.Add(newVideo);
                context.SaveChanges();
            }

            // SQL sentences generated by Entity Framework by ckecking with LINQPad:
            
            //--Region Parameters
            // DECLARE @0 NVarChar(255) = 'Terminator 1'
            // DECLARE @1 DateTime2 = '1984-10-26 00:00:00.0000000'
            // DECLARE @2 TinyInt = 1
            // DECLARE @3 TinyInt = 1
            // -- EndRegion
            // INSERT[dbo].[Videos] ([Name], [ReleaseDate], [GenreId], [Classification])
            // VALUES(@0, @1, @2, @3)
            // SELECT[Id]
            // FROM[dbo].[Videos]
            // WHERE @@ROWCOUNT > 0 AND[Id] = scope_identity()

        }
        static void Main(string[] args)
        {
            //AddNewVideo();
        }
    }
}
